import type { WalletStateV1 } from "../src/wallet/types.js";
import type { MiningRuntimeStatusV1 } from "../src/wallet/mining/types.js";
import type { MiningControlPlaneView } from "../src/wallet/mining/types.js";
import { createWalletReadModel } from "../src/wallet/read/project.js";

export function createMiningState(overrides: Partial<WalletStateV1["miningState"]> = {}): WalletStateV1["miningState"] {
  return {
    runMode: "stopped",
    state: "idle",
    pauseReason: null,
    currentPublishState: "none",
    currentDomain: null,
    currentDomainId: null,
    currentDomainIndex: null,
    currentSenderScriptPubKeyHex: null,
    currentTxid: null,
    currentWtxid: null,
    currentFeeRateSatVb: null,
    currentAbsoluteFeeSats: null,
    currentScore: null,
    currentSentence: null,
    currentEncodedSentenceBytesHex: null,
    currentBip39WordIndices: null,
    currentBlendSeedHex: null,
    currentBlockTargetHeight: null,
    currentReferencedBlockHashDisplay: null,
    currentIntentFingerprintHex: null,
    livePublishInMempool: null,
    currentPublishDecision: null,
    replacementCount: 0,
    currentBlockFeeSpentSats: "0",
    sessionFeeSpentSats: "0",
    lifetimeFeeSpentSats: "0",
    sharedMiningConflictOutpoint: null,
    ...overrides,
  };
}

export function createWalletState(overrides: Partial<WalletStateV1> = {}): WalletStateV1 {
  return {
    schemaVersion: 5,
    stateRevision: 1,
    lastWrittenAtUnixMs: 1,
    walletRootId: "wallet-root",
    network: "mainnet",
    localScriptPubKeyHexes: [],
    mnemonic: {
      phrase: `${"abandon ".repeat(23)}art`,
      language: "english",
    },
    keys: {
      masterFingerprintHex: "11".repeat(4),
      accountPath: "m/84'/0'/0'",
      accountXprv: "xprv-test",
      accountXpub: "xpub-test",
    },
    descriptor: {
      privateExternal: "wpkh(xprv-test/0/*)",
      publicExternal: "wpkh(xpub-test/0/*)",
      checksum: "abcd1234",
      rangeEnd: 10,
      safetyMargin: 5,
    },
    funding: {
      address: "bc1qfunding",
      scriptPubKeyHex: "0014" + "11".repeat(20),
    },
    walletBirthTime: 123,
    managedCoreWallet: {
      walletName: "wallet.dat",
      internalPassphrase: "passphrase",
      descriptorChecksum: "abcd1234",
      walletAddress: "bc1qfunding",
      walletScriptPubKeyHex: "0014" + "11".repeat(20),
      proofStatus: "ready",
      lastImportedAtUnixMs: null,
      lastVerifiedAtUnixMs: null,
    },
    domains: [],
    miningState: createMiningState(),
    pendingMutations: [],
    ...overrides,
  };
}

export function createMiningRuntimeStatus(
  overrides: Partial<MiningRuntimeStatusV1> = {},
): MiningRuntimeStatusV1 {
  return {
    schemaVersion: 1,
    walletRootId: "wallet-root",
    workerApiVersion: "cogcoin/mining-worker/v1",
    workerBinaryVersion: "1.1.6",
    workerBuildId: "build-1",
    updatedAtUnixMs: 1,
    runMode: "stopped",
    backgroundWorkerPid: null,
    backgroundWorkerRunId: null,
    backgroundWorkerHeartbeatAtUnixMs: null,
    backgroundWorkerHealth: null,
    indexerDaemonState: "synced",
    indexerDaemonInstanceId: null,
    indexerSnapshotSeq: null,
    indexerSnapshotOpenedAtUnixMs: null,
    indexerTruthSource: undefined,
    indexerHeartbeatAtUnixMs: null,
    coreBestHeight: null,
    coreBestHash: null,
    indexerTipHeight: null,
    indexerTipHash: null,
    indexerReorgDepth: null,
    indexerTipAligned: null,
    corePublishState: "healthy",
    providerState: "ready",
    lastSuspendDetectedAtUnixMs: null,
    reconnectSettledUntilUnixMs: null,
    tipSettledUntilUnixMs: null,
    miningState: "idle",
    currentPhase: "idle",
    currentPublishState: "none",
    targetBlockHeight: null,
    referencedBlockHashDisplay: null,
    currentDomainId: null,
    currentDomainName: null,
    currentSentenceDisplay: null,
    currentCanonicalBlend: null,
    currentTxid: null,
    currentWtxid: null,
    livePublishInMempool: null,
    currentFeeRateSatVb: null,
    currentAbsoluteFeeSats: null,
    currentBlockFeeSpentSats: "0",
    sessionFeeSpentSats: "0",
    lifetimeFeeSpentSats: "0",
    sameDomainCompetitorSuppressed: null,
    higherRankedCompetitorDomainCount: null,
    dedupedCompetitorDomainCount: null,
    competitivenessGateIndeterminate: null,
    mempoolSequenceCacheStatus: null,
    currentPublishDecision: null,
    lastMempoolSequence: null,
    lastCompetitivenessGateAtUnixMs: null,
    pauseReason: null,
    providerConfigured: true,
    providerKind: "openai",
    bitcoindHealth: "ready",
    bitcoindServiceState: "ready",
    bitcoindReplicaStatus: "ready",
    nodeHealth: "synced",
    indexerHealth: "synced",
    tipsAligned: true,
    lastEventAtUnixMs: null,
    lastError: null,
    note: null,
    ...overrides,
  };
}

export function createMiningControlPlaneView(
  overrides: Partial<MiningControlPlaneView> = {},
): MiningControlPlaneView {
  return {
    runtime: createMiningRuntimeStatus(),
    provider: {
      configured: true,
      provider: "openai",
      status: "ready",
      message: null,
      modelId: "gpt-5.4-mini",
      effectiveModel: "gpt-5.4-mini",
      modelOverride: null,
      modelSelectionSource: "legacy-default",
      usingDefaultModel: true,
      extraPromptConfigured: false,
      estimatedDailyCostUsd: null,
      estimatedDailyCostDisplay: null,
    },
    lastEventAtUnixMs: null,
    ...overrides,
  };
}

export function createWalletReadContext(overrides: Record<string, unknown> = {}) {
  const state = createWalletState();
  const model = createWalletReadModel(state, null);
  return {
    databasePath: "/tmp/test.db",
    dataDir: "/tmp",
    localState: {
      availability: "ready",
      clientPasswordReadiness: "ready",
      unlockRequired: false,
      walletRootId: state.walletRootId,
      state,
      source: "primary",
      hasPrimaryStateFile: true,
      hasBackupStateFile: false,
      message: null,
    },
    snapshot: null,
    model,
    bitcoind: {
      health: "ready",
      message: null,
      status: null,
    },
    indexer: {
      health: "synced",
      message: null,
      status: null,
      source: null,
      daemonInstanceId: null,
      snapshotSeq: null,
      openedAtUnixMs: null,
      snapshotTip: null,
    },
    nodeHealth: "synced",
    nodeMessage: null,
    nodeStatus: {
      chain: "mainnet",
      nodeBestHeight: null,
      nodeBestHashHex: null,
      walletReplica: {
        proofStatus: "ready",
      },
    },
    fundingSpendableSats: 0n,
    mining: undefined,
    ...overrides,
  } as any;
}
