export const PROGRESS_TICK_MS = 250;
export const PREPARING_SYNC_LINE = "Preparing managed Cogcoin sync...";
export const ART_WIDTH = 80;
export const ART_HEIGHT = 13;
export const INTRO_ENTRY_MS = 5_000;
export const INTRO_PAUSE_MS = 5_000;
export const INTRO_EXIT_MS = 5_000;
export const INTRO_TOTAL_MS = INTRO_ENTRY_MS + INTRO_PAUSE_MS + INTRO_EXIT_MS;
export const STATUS_ELLIPSIS_WIDTH = 3;
export const STATUS_ELLIPSIS_TICK_MS = 500;
export const NEUTRAL_MESSAGE_TITLE = "⛭  C O G C O I N  ⛭";
export const MESSAGE_FIELD_ROW = 1;
export const STATUS_FIELD_ROW = 12;
export const FIELD_LEFT = 8;
export const FIELD_WIDTH = 64;
export const SCROLL_WINDOW_LEFT = 7;
export const SCROLL_WINDOW_TOP = 3;
export const SCROLL_WINDOW_WIDTH = 65;
export const SCROLL_WINDOW_HEIGHT = 8;
export const TRAIN_CLIP_MIN_COLUMN = -1;
export const TRAIN_CLIP_MAX_COLUMN = SCROLL_WINDOW_WIDTH;
export const MAX_QUOTE_LINES = 6;
export const TRAIN_SPRITE_WIDTH = 64;
export const TRAIN_SPRITE_HEIGHT = 6;
export const TRAIN_SPRITE_TOP = SCROLL_WINDOW_TOP + Math.floor((SCROLL_WINDOW_HEIGHT - TRAIN_SPRITE_HEIGHT) / 2);
export const TRAIN_CENTER_X = Math.round((SCROLL_WINDOW_WIDTH - TRAIN_SPRITE_WIDTH) / 2);
export const TRAIN_OFFSCREEN_LEFT_X = -TRAIN_SPRITE_WIDTH - 1;
export const TRAIN_OFFSCREEN_RIGHT_X = SCROLL_WINDOW_WIDTH + 1;
export const FOLLOW_CAR_WIDTH = 9;
export const FOLLOW_CAR_PITCH = 8;
export const FOLLOW_CAR_HEIGHT = 6;
export const FOLLOW_WINDOW_LEFT = SCROLL_WINDOW_LEFT - 1;
export const FOLLOW_WINDOW_WIDTH = SCROLL_WINDOW_WIDTH + 3;
export const FOLLOW_CAR_TOP = SCROLL_WINDOW_TOP + Math.floor((SCROLL_WINDOW_HEIGHT - FOLLOW_CAR_HEIGHT) / 2) - 2;
export const FOLLOW_AGE_ROW = FOLLOW_CAR_TOP + FOLLOW_CAR_HEIGHT;
export const FOLLOW_CENTER_SLOT_X = Math.floor((FOLLOW_WINDOW_WIDTH - FOLLOW_CAR_WIDTH) / 2);
export const FOLLOW_CONNECTION_SLOT_X = FOLLOW_CENTER_SLOT_X - FOLLOW_CAR_PITCH;
export const FOLLOW_PENDING_SLOT_X = 0;
export const FOLLOW_PENDING_OFFSCREEN_LEFT_X = -FOLLOW_CAR_WIDTH;
export const FOLLOW_CLIP_MIN_COLUMN = 0;
export const FOLLOW_CLIP_MAX_COLUMN = FOLLOW_WINDOW_WIDTH - 1;
export const FOLLOW_RIGHT_SLOT_XS = [
  FOLLOW_CENTER_SLOT_X + FOLLOW_CAR_PITCH,
  FOLLOW_CENTER_SLOT_X + (FOLLOW_CAR_PITCH * 2),
  FOLLOW_CENTER_SLOT_X + (FOLLOW_CAR_PITCH * 3),
  FOLLOW_CENTER_SLOT_X + (FOLLOW_CAR_PITCH * 4),
] as const;
export const FOLLOW_PENDING_LABEL = "~10 min";
export const FOLLOW_PENDING_ENTER_MS = 1_000;
export const FOLLOW_APPROACH_MS = 3_000;
export const FOLLOW_FAST_APPROACH_MS = 1_000;
export const FOLLOW_SHIFT_MS = 1_000;
export const FOLLOW_FAST_SHIFT_MS = 1_000;
